image: docker:dind

stages:
  - build

variables:
  DOCKER_DRIVER: overlay

.job_template: &job_definition
  services:
    - docker:dind
  tags:
    - docker
  before_script:
    - export IMAGE_TAG=$(if [ ! -z "$CI_COMMIT_TAG" ]; then echo "$CI_COMMIT_TAG"; else echo "latest"; fi)
    - export APP_IMAGE="$CI_REGISTRY_IMAGE:$IMAGE_TAG"

build_image:
  <<: *job_definition
  stage: build
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker build -t $APP_IMAGE .
    - docker push $CI_REGISTRY_IMAGE:$IMAGE_TAG
