# Generated by Django 2.0.2 on 2018-02-12 12:16

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='testjson',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
