# Generated by Django 2.0.2 on 2018-02-12 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_room_testjson'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='documents',
        ),
    ]
