# Generated by Django 2.0.2 on 2018-02-12 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_remove_room_documents'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='testjson',
            new_name='documents',
        ),
    ]
