# Generated by Django 2.0.2 on 2018-02-12 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0004_auto_20180212_1234'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Room',
        ),
    ]
