# Generated by Django 2.0.2 on 2018-02-21 13:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commons', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='documents',
            new_name='survey',
        ),
        migrations.RemoveField(
            model_name='room',
            name='account_id',
        ),
        migrations.AlterField(
            model_name='room',
            name='name',
            field=models.CharField(max_length=200, verbose_name="this is your room's name"),
        ),
        migrations.AlterField(
            model_name='room',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
