# Generated by Django 2.0.2 on 2018-02-23 18:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commons', '0002_auto_20180223_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='guests',
            field=models.ManyToManyField(related_name='guestInRooms', to=settings.AUTH_USER_MODEL),
        ),
    ]
