# Generated by Django 2.0.3 on 2018-04-24 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserRoomM2M',
            new_name='GuestRoomRelation',
        ),
    ]
