# Generated by Django 2.0.3 on 2018-04-24 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20180424_1153'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='guestroomrelation',
            unique_together={('guest', 'room_guest')},
        ),
    ]
