# Generated by Django 2.0.2 on 2018-03-02 00:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_answer_room'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='jwt_secret',
        ),
    ]
