# Generated by Django 2.0.2 on 2018-03-13 12:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20180313_1225'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user',
            field=models.ManyToManyField(related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
