# Generated by Django 2.0.3 on 2018-04-26 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20180426_0937'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guestroomrelation',
            old_name='guest',
            new_name='user',
        ),
        migrations.AlterUniqueTogether(
            name='guestroomrelation',
            unique_together={('user', 'room_guest')},
        ),
    ]
