# Generated by Django 2.0.3 on 2018-05-16 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20180426_1059'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomanswer',
            name='guestRoomRelation_id',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answer_detail', to='core.GuestRoomRelation'),
        ),
    ]
