# Generated by Django 2.0.2 on 2018-03-14 10:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20180313_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='guests',
            field=models.ManyToManyField(related_name='rooms_guests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='roomanswer',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guests_answers', to='core.Room'),
        ),
    ]
