# Generated by Django 2.0.3 on 2018-05-16 08:39

from django.db import migrations


def add_one2one_field(apps, schema_editor):
    RoomAnswer = apps.get_model('core', 'RoomAnswer')
    GuestRoomRelation = apps.get_model('core', 'GuestRoomRelation')
    for ansObj in RoomAnswer.objects.all():
        guestRoomObj = GuestRoomRelation.objects.get(room_guest=ansObj.room, user=ansObj.user)
        ansObj.guestRoomRelation_id = guestRoomObj
        ansObj.save()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_roomanswer_guestroomrelation_id'),
    ]

    operations = [
        migrations.RunPython(add_one2one_field),
    ]
