# Generated by Django 2.0.3 on 2018-05-16 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_make_one2one_on_roomAnswer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roomanswer',
            old_name='guestRoomRelation_id',
            new_name='guest_room_relation',
        ),
        migrations.AlterUniqueTogether(
            name='roomanswer',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='roomanswer',
            name='room',
        ),
        migrations.RemoveField(
            model_name='roomanswer',
            name='user',
        ),
    ]
