# Generated by Django 2.0.3 on 2018-05-18 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20180516_1309'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guestroomrelation',
            old_name='join_date',
            new_name='request_date',
        ),
        migrations.AddField(
            model_name='guestroomrelation',
            name='accept_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='guestroomrelation',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
    ]
