# Generated by Django 2.0.3 on 2018-05-22 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20180518_1528'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guestroomrelation',
            old_name='room_guest',
            new_name='room',
        ),
        migrations.AlterUniqueTogether(
            name='guestroomrelation',
            unique_together={('user', 'room')},
        ),
    ]
