# Generated by Django 2.0.3 on 2018-05-25 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20180522_1343'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='published_at',
            field=models.DateTimeField(null=True),
        ),
    ]
