# Generated by Django 2.0.3 on 2018-06-03 18:13

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20180525_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='survey',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=list),
        ),
    ]
