# Generated by Django 2.0.3 on 2018-06-04 06:04

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20180603_1813'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomanswer',
            name='submitted_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='roomanswer',
            name='answer',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=list),
        ),
    ]
