# Generated by Django 2.0.3 on 2018-06-05 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20180604_0604'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='have_survey_when_published',
            field=models.BooleanField(default=True),
        ),
    ]
