# Generated by Django 2.0.3 on 2018-06-05 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_room_have_survey_when_published'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roomanswer',
            old_name='created_at',
            new_name='first_saved_at',
        ),
        migrations.AddField(
            model_name='roomanswer',
            name='submitted',
            field=models.BooleanField(default=False),
        ),
    ]
