# Generated by Django 2.0.6 on 2018-06-22 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20180605_1544'),
    ]

    operations = [
        migrations.AddField(
            model_name='guestroomrelation',
            name='created_by_room_owner',
            field=models.BooleanField(default=False),
        ),
    ]
