# Generated by Django 2.0.6 on 2018-06-23 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_guestroomrelation_created_by_room_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomanswer',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
