# Generated by Django 2.0.6 on 2018-07-19 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_room_attached_links'),
    ]

    operations = [
        migrations.AddField(
            model_name='guestroomrelation',
            name='expire_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='guest_ttl_in_days',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='last_date_to_join',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
