# Generated by Django 2.1 on 2018-08-18 01:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_auto_20180817_2241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guestroomrelation',
            name='accepted',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='guestroomrelation',
            name='created_by_room_owner',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='roomanswer',
            name='guest_room_relation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='answer_detail', to='core.GuestRoomRelation'),
        ),
        migrations.AlterField(
            model_name='roomanswer',
            name='submitted',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
