# Generated by Django 2.0.2 on 2018-02-27 15:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='jwt_secret',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
